#!/bin/bash

set -o errexit

HOST=$(head -n1 $1 | awk '{ print $2}')
CUSTOM_URL="http://$HOST:8090"

if [ ! -d tests ]; then
  echo 'no tests specifications found'
  exit 0
fi

pushd ./tests

rainforest validate --token $RAINFOREST_TOKEN

rainforest upload --token $RAINFOREST_TOKEN

rainforest run --token $RAINFOREST_TOKEN \
           --tag automated \
           --site-id 5822 \
           --fail-fast \
           --custom-url $CUSTOM_URL \
           --description "wercker build for ${WERCKER_GIT_COMMIT:0:8}" \
           --fg
